### PR TITLE
Added OSM to demo

### LINKED ISSUE #9: Errors after changing map-type attribute
Many errors thrown after changing the gn-map "map-type" attribute from default "GoogleMap" to "OpenStreetMap" ..

"Uncaught exception(anonymous function) @ polymer.html:1564Polymer.Base._addFeature._notifyListener @ polymer.html:2016(anonymous function) @ polymer.html:1588Polymer.Base._addFeature.fire @ polymer.html:1335Polymer.Bind._modelApi._notifyChange @ polymer.html:1428Polymer.Base.extend._notifyEffect @ polymer.html:1611Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445setter @ polymer.html:1524(anonymous function) @ polymer.html:3726
polymer.html:1335 Uncaught exceptionPolymer.Base._addFeature.fire @ polymer.html:1335Polymer.Bind._modelApi._notifyChange @ polymer.html:1428Polymer.Base.extend._notifyEffect @ polymer.html:1611Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445setter @ polymer.html:1524(anonymous function) @ polymer.html:3726Polymer.Base.extend._functionEffect @ polymer.html:1615Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445
polymer.html:3726 Uncaught exception(anonymous function) @ polymer.html:3726Polymer.Base.extend._functionEffect @ polymer.html:1615Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445setter @ polymer.html:1524(anonymous function) @ polymer.html:1566Polymer.Base._addFeature._notifyListener @ polymer.html:2016(anonymous function) @ polymer.html:1588Polymer.Base._addFeature.fire @ polymer.html:1335Polymer.Bind._modelApi._notifyChange @ polymer.html:1428Polymer.Base.extend._notifyEffect @ polymer.html:1611
polymer-mini.html:729 Uncaught exceptionDomApi.setAttribute @ polymer-mini.html:729Polymer.Base._addFeature.serializeValueToAttribute @ polymer-micro.html:602Polymer.Base._addFeature.serializeValueToAttribute @ polymer.html:3417Polymer.Base._addFeature.reflectPropertyToAttribute @ polymer-micro.html:593Polymer.Base.extend._reflectEffect @ polymer.html:1607Polymer.Bind._modelApi._effectEffects @ polymer.html:1461Polymer.Bind._modelApi._propertySetter @ polymer.html:1445Polymer.Bind._modelApi.__setProperty @ polymer.html:1454Polymer.Base._addFeature._applyEffectValue @ polymer.html:1906Polymer.Base.extend._annotationEffect @ polymer.html:1603"

.. 

screen

Don't know if this is a polymer or an internal problem.

### PR DESCRIPTION
**Pull request by jinankjain**
Fixes #9 @fabianbormann have a look at this :)

### CODE REVIEW

**Comment by fabianbormann** [comment]
Hey @jinankjain, your changes will not solve the errors related to #9, but I realized that we do not need the google-maps imports in the demo too, because it's enough to import gn-map which still imports google-map and osm-map. ;)

**Comment by fabianbormann** [comment]
Can you change your pull-request by removing google-maps lines

`
<link rel="import" href="../../google-map/google-map.html">
<link rel="import" href="../../google-map/google-map-poly.html">
<link rel="import" href="../../google-map/google-map-point.html">
`

from the demo?

**Comment by jinankjain** [comment]
@fabianbormann I have done that

**Comment by fabianbormann** [comment]
@jinankjain nice thank you!

**Pull request merged**
